runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1m"

skip_files:
- \.gitignore
- ^\.git/.*
- ^node_modules/(.*/)?

libraries:
- name: webapp2
  version: "2.5.2"

builtins:
- deferred: on

handlers:

- url: /
  static_files: ui/index.html
  upload: ui/index.html

- url: /dist  # The UI code bundle folder (not used in this example)
  static_dir: ui/dist

- url: /my-cron-job/.*
  script: backend.main.app

- url: /(.*\..*)$  # a file in the root level
  static_files: ui/dist/\1
  upload: ui/dist/.*\..*$

- url: /(.*)$  # not a file, i.e. front end routes
  static_files: ui/dist/index.html
  upload: ui/dist/index.html
